// Generated by make_lang.py

LangDef lang_table[29] = {
 // en_US
  { 0, RESOURCE_ID_EN_US_NAMES }, // 0 = English
 // [b'Sun', b'Mon', b'Tue', b'Wed', b'Thu', b'Fri', b'Sat', b'Jan', b'Feb', b'Mar', b'Apr', b'May', b'Jun', b'Jul', b'Aug', b'Sep', b'Oct', b'Nov', b'Dec', b'am', b'pm']

 // fr_FR
  { 0, RESOURCE_ID_FR_FR_NAMES }, // 1 = French
 // [b'Dim', b'Lun', b'Mar', b'Mer', b'Jeu', b'Ven', b'Sam', b'Janv', 'Févr', b'Mars', b'Avr', b'Mai', b'Juin', b'Juil', 'Août', b'Sept', b'Oct', b'Nov', 'Déc', b'am', b'pm']

 // it_IT
  { 0, RESOURCE_ID_IT_IT_NAMES }, // 2 = Italian
 // [b'Dom', b'Lun', b'Mar', b'Mer', b'Gio', b'Ven', b'Sab', b'Gen', b'Feb', b'Mar', b'Apr', b'Mag', b'Giu', b'Lug', b'Ago', b'Set', b'Ott', b'Nov', b'Dic', b'am', b'pm']

 // es_ES
  { 0, RESOURCE_ID_ES_ES_NAMES }, // 3 = Spanish
 // [b'Dom', b'Lun', b'Mar', 'Mié', b'Jue', b'Vie', 'Sáb', b'Ene', b'Feb', b'Mar', b'Abr', b'May', b'Jun', b'Jul', b'Ago', b'Sept', b'Oct', b'Nov', b'Dic', b'am', b'pm']

 // pt_PT
  { 0, RESOURCE_ID_PT_PT_NAMES }, // 4 = Portuguese
 // [b'D', b'S', b'T', b'Q', b'Q', b'S', b'S', b'Jan', b'Fev', b'Mar', b'Abr', b'Mai', b'Jun', b'Jul', b'Ago', b'Set', b'Out', b'Nov', b'Dez', b'am', b'pm']

 // de_DE
  { 0, RESOURCE_ID_DE_DE_NAMES }, // 5 = German
 // [b'So', b'Mo', b'Di', b'Mi', b'Do', b'Fr', b'Sa', b'Jan', b'Feb', 'März', b'Apr', b'Mai', b'Juni', b'Juli', b'Aug', b'Sept', b'Okt', b'Nov', b'Dez', b'vorm', b'nach']

 // nl_NL
  { 0, RESOURCE_ID_NL_NL_NAMES }, // 6 = Dutch
 // [b'Zo', b'Ma', b'Di', b'Wo', b'Do', b'Vr', b'Za', b'Jan', b'Feb', b'Mrt', b'Apr', b'Mei', b'Jun', b'Jul', b'Aug', b'Sep', b'Okt', b'Nov', b'Dec', b'am', b'pm']

 // da_DK
  { 0, RESOURCE_ID_DA_DK_NAMES }, // 7 = Danish
 // ['Søn', b'Man', b'Tirs', b'Ons', b'Tors', b'Fre', 'Lør', b'Jan', b'Feb', b'Mar', b'Apr', b'Maj', b'Jun', b'Jul', b'Aug', b'Sep', b'Okt', b'Nov', b'Dec', b'am', b'pm']

 // sv_SE
  { 0, RESOURCE_ID_SV_SE_NAMES }, // 8 = Swedish
 // ['Sön', 'Mån', b'Tis', b'Ons', b'Tors', b'Fre', 'Lör', b'Jan', b'Feb', b'Mars', b'Apr', b'Maj', b'Juni', b'Juli', b'Aug', b'Sep', b'Okt', b'Nov', b'Dec', b'fm', b'em']

 // is_IS
  { 0, RESOURCE_ID_IS_IS_NAMES }, // 9 = Icelandic
 // [b'Sun', 'Mán', 'Þri', 'Mið', b'Fim', 'Fös', b'Lau', b'Jan', b'Feb', b'Mar', b'Apr', 'Maí', 'Jún', 'Júl', 'Ágú', b'Sep', b'Okt', 'Nóv', b'Des', b'fh', b'eh']

 // tl
  { 0, RESOURCE_ID_TL_NAMES }, // 10 = Tagalog
 // [b'Lin', b'Lun', b'Mar', b'Miy', b'Huw', b'Biy', b'Sab', b'Ene', b'Peb', b'Mar', b'Abr', b'May', b'Hun', b'Hul', b'Ago', b'Set', b'Okt', b'Nob', b'Dis', b'am', b'pm']

 // el_GR
  { 1, RESOURCE_ID_EL_GR_NAMES }, // 11 = Greek
 // ['Κυρ', 'Δευ', 'Τρί', 'Τετ', 'Πέμ', 'Παρ', 'Σάβ', 'Ιαν', 'Φεβ', 'Μαρ', 'Απρ', 'Μαΐ', 'Ιουν', 'Ιουλ', 'Αυγ', 'Σεπ', 'Οκτ', 'Νοε', 'Δεκ', 'πμ', 'μμ']

 // hu_HU
  { 0, RESOURCE_ID_HU_HU_NAMES }, // 12 = Hungarian
 // [b'V', b'H', b'K', b'Sze', b'Cs', b'P', b'Szo', b'J', b'F', b'M', 'Á', b'M', b'J', b'J', b'A', b'Sz', b'O', b'N', b'D', b'de', b'du']

 // ru_RU
  { 2, RESOURCE_ID_RU_RU_NAMES }, // 13 = Russian
 // ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн', 'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек', 'до', 'посл']

 // pl_PL
  { 0, RESOURCE_ID_PL_PL_NAMES }, // 14 = Polish
 // [b'N', b'P', b'W', 'Ś', b'C', b'P', b'S', b'Sty', b'Lut', b'Mar', b'Kwi', b'Maj', b'Cze', b'Lip', b'Sie', b'Wrz', 'Paź', b'Lis', b'Gru', b'am', b'pm']

 // cs_CZ
  { 0, RESOURCE_ID_CS_CZ_NAMES }, // 15 = Czech
 // [b'Ne', b'Po', 'Út', b'St', 'Čt', 'Pá', b'So', b'Led', 'Úno', 'Bře', b'Dub', 'Kvě', 'Čvn', 'Čvc', b'Srp', 'Zář', 'Říj', b'Lis', b'Pro', b'dop', b'odp']

 // hy_AM
  { 3, RESOURCE_ID_HY_AM_NAMES }, // 16 = Armenian
 // ['Կիր', 'Երկ', 'Երք', 'Չրք', 'Հնգ', 'Ուր', 'Շբթ', 'Հնվ', 'Փտվ', 'Մրտ', 'Ապր', 'Մյս', 'Հնս', 'Հլս', 'Օգս', 'Սեպ', 'Հոկ', 'Նոյ', 'Դեկ', 'առաջ', 'հետո']

 // tr_TR
  { 0, RESOURCE_ID_TR_TR_NAMES }, // 17 = Turkish
 // [b'Paz', b'Pzt', b'Sal', 'Çar', b'Per', b'Cum', b'Cmt', b'Oca', 'Şub', b'Mar', b'Nis', b'May', b'Haz', b'Tem', 'Ağu', b'Eyl', b'Eki', b'Kas', b'Ara', 'öö', 'ös']

 // he_IL
  { 4, RESOURCE_ID_HE_IL_NAMES }, // 18 = Hebrew
 // ['׳א', '׳ב', '׳ג', '׳ד', '׳ה', '׳ו', '׳ש', '׳וני', '׳רבפ', 'ץרמ', '׳רפא', 'יאמ', 'ינוי', 'ילוי', '׳גוא', '׳טפס', '׳קוא', '׳בונ', '׳מצד', b'am', b'pm']

 // fa_IR
  { 5, RESOURCE_ID_FA_IR_NAMES }, // 19 = Farsi
 // ['ی', 'د', 'س', 'چ', 'پ', 'ج', 'ش', 'ژ', 'ف', 'م', 'آ', 'م', 'ژ', 'ژ', 'ا', 'س', 'ا', 'ن', 'د', 'ص', 'م']

 // ar_SA
  { 5, RESOURCE_ID_AR_SA_NAMES }, // 20 = Arabic
 // ['ح', 'ن', 'ث', 'ر', 'خ', 'ج', 'س', 'ي', 'ف', 'م', 'أ', 'و', 'ن', 'ل', 'غ', 'س', 'ك', 'ب', 'د', 'ص', 'م']

 // zh_CN
  { 6, RESOURCE_ID_ZH_CN_NAMES }, // 21 = Chinese
 // ['周日', '周一', '周二', '周三', '周四', '周五', '周六', '1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月', '上午', '下午']

 // ja_JP
  { 7, RESOURCE_ID_JA_JP_NAMES }, // 22 = Japanese
 // ['日', '月', '火', '水', '木', '金', '土', '1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月', '午前', '午後']

 // ko_KR
  { 8, RESOURCE_ID_KO_KR_NAMES }, // 23 = Korean
 // ['일', '월', '화', '수', '목', '금', '토', '1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월', '오전', '오후']

 // th_TH
  { 9, RESOURCE_ID_TH_TH_NAMES }, // 24 = Thai
 // ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส', 'มค', 'กพ', 'มีค', 'เมย', 'พค', 'มิย', 'กค', 'สค', 'กย', 'ตค', 'พย', 'ธค', 'ก่อน', 'หลัง']

 // ta_IN
  { 10, RESOURCE_ID_TA_IN_NAMES }, // 25 = Tamil
 // ['ஞாயி', 'திங்', 'செவ்', 'புத', 'வியா', 'வெள்', 'சனி', 'ஜன', 'பிப்', 'மார்', 'ஏப்', 'மே', 'ஜூன்', 'ஜூலை', 'ஆக', 'செப்', 'அக்', 'நவ', 'டிச', 'மு', 'பி']

 // hi_IN
  { 11, RESOURCE_ID_HI_IN_NAMES }, // 26 = Hindi
 // ['र', 'सो', 'मं', 'बु', 'गु', 'शु', 'श', 'ज', 'फ़', 'मा', 'अ', 'म', 'जू', 'जु', 'अ', 'सि', 'अ', 'न', 'दि', 'पूर्व', 'अपर']

 // bg_BG
  { 2, RESOURCE_ID_BG_BG_NAMES }, // 27 = Bulgarian
 // ['Нд', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Яну', 'Фев', 'Март', 'Апр', 'Май', 'Юни', 'Юли', 'Авг', 'Сеп', 'Окт', 'Ное', 'Дек', 'проб', 'слоб']

 // nb_NO
  { 0, RESOURCE_ID_NB_NO_NAMES }, // 28 = Norwegian
 // ['Søn', b'Man', b'Tir', b'Ons', b'Tor', b'Fre', 'Lør', b'Jan', b'Feb', b'Mars', b'Apr', b'Mai', b'Juni', b'Juli', b'Aug', b'Sep', b'Okt', b'Nov', b'Des', b'am', b'pm']

};

int num_langs = 29;
// maximum characters: 15
#define DATE_NAMES_MAX_BUFFER 221

#define NUM_DATE_LANG_FONTS 12
struct FontPlacement date_lang_font_placement[NUM_DATE_LANG_FONTS] = {
#if defined(PBL_PLATFORM_GABBRO)
{ RESOURCE_ID_DAY_FONT_LATIN_26, -1 },
{ RESOURCE_ID_DAY_FONT_EL_23, 1 },
{ RESOURCE_ID_DAY_FONT_RU_23, 1 },
{ RESOURCE_ID_DAY_FONT_HY_23, 1 },
{ RESOURCE_ID_DAY_FONT_RTL_HE_23, 1 },
{ RESOURCE_ID_DAY_FONT_RTL_AR_23, 1 },
{ RESOURCE_ID_DAY_FONT_ZH_26, -1 },
{ RESOURCE_ID_DAY_FONT_JA_26, -1 },
{ RESOURCE_ID_DAY_FONT_KO_26, -2 },
{ RESOURCE_ID_DAY_FONT_TH_26, -1 },
{ RESOURCE_ID_DAY_FONT_TA_26, -2 },
{ RESOURCE_ID_DAY_FONT_HI_26, 0 },
#elif defined(PBL_PLATFORM_EMERY)
{ RESOURCE_ID_DAY_FONT_LATIN_22, -1 },
{ RESOURCE_ID_DAY_FONT_EL_19, 1 },
{ RESOURCE_ID_DAY_FONT_RU_19, 1 },
{ RESOURCE_ID_DAY_FONT_HY_19, 1 },
{ RESOURCE_ID_DAY_FONT_RTL_HE_19, 1 },
{ RESOURCE_ID_DAY_FONT_RTL_AR_19, 1 },
{ RESOURCE_ID_DAY_FONT_ZH_22, -1 },
{ RESOURCE_ID_DAY_FONT_JA_22, -1 },
{ RESOURCE_ID_DAY_FONT_KO_22, -2 },
{ RESOURCE_ID_DAY_FONT_TH_22, -1 },
{ RESOURCE_ID_DAY_FONT_TA_22, -2 },
{ RESOURCE_ID_DAY_FONT_HI_22, 0 },
#elif defined(PBL_PLATFORM_APLITE) || defined(PBL_PLATFORM_BASALT) || defined(PBL_PLATFORM_DIORITE)
{ RESOURCE_ID_DAY_FONT_LATIN_16, -1 },
{ RESOURCE_ID_DAY_FONT_EL_14, 1 },
{ RESOURCE_ID_DAY_FONT_RU_14, 1 },
{ RESOURCE_ID_DAY_FONT_HY_14, 1 },
{ RESOURCE_ID_DAY_FONT_RTL_HE_14, 1 },
{ RESOURCE_ID_DAY_FONT_RTL_AR_14, 1 },
{ RESOURCE_ID_DAY_FONT_ZH_16, -1 },
{ RESOURCE_ID_DAY_FONT_JA_16, -1 },
{ RESOURCE_ID_DAY_FONT_KO_16, -2 },
{ RESOURCE_ID_DAY_FONT_TH_16, -1 },
{ RESOURCE_ID_DAY_FONT_TA_16, -2 },
{ RESOURCE_ID_DAY_FONT_HI_16, 0 },
#elif defined(PBL_PLATFORM_CHALK)
{ RESOURCE_ID_DAY_FONT_LATIN_18, -1 },
{ RESOURCE_ID_DAY_FONT_EL_16, 1 },
{ RESOURCE_ID_DAY_FONT_RU_16, 1 },
{ RESOURCE_ID_DAY_FONT_HY_16, 1 },
{ RESOURCE_ID_DAY_FONT_RTL_HE_16, 1 },
{ RESOURCE_ID_DAY_FONT_RTL_AR_16, 1 },
{ RESOURCE_ID_DAY_FONT_ZH_18, -1 },
{ RESOURCE_ID_DAY_FONT_JA_18, -1 },
{ RESOURCE_ID_DAY_FONT_KO_18, -2 },
{ RESOURCE_ID_DAY_FONT_TH_18, -1 },
{ RESOURCE_ID_DAY_FONT_TA_18, -2 },
{ RESOURCE_ID_DAY_FONT_HI_18, 0 },
#endif
};
