// Generated by make_lang.py

LangDef lang_table[29] = {
 // en_US
  { 0, RESOURCE_ID_EN_US_NAMES }, // 0 = English
 // ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'am', 'pm']

 // fr_FR
  { 0, RESOURCE_ID_FR_FR_NAMES }, // 1 = French
 // ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam', 'Janv', u'F\xe9vr', 'Mars', 'Avr', 'Mai', 'Juin', 'Juil', u'Ao\xfbt', 'Sept', 'Oct', 'Nov', u'D\xe9c', 'am', 'pm']

 // it_IT
  { 0, RESOURCE_ID_IT_IT_NAMES }, // 2 = Italian
 // ['Dom', 'Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab', 'Gen', 'Feb', 'Mar', 'Apr', 'Mag', 'Giu', 'Lug', 'Ago', 'Set', 'Ott', 'Nov', 'Dic', 'am', 'pm']

 // es_ES
  { 0, RESOURCE_ID_ES_ES_NAMES }, // 3 = Spanish
 // ['Dom', 'Lun', 'Mar', u'Mi\xe9', 'Jue', 'Vie', u'S\xe1b', 'Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sept', 'Oct', 'Nov', 'Dic', 'am', 'pm']

 // pt_PT
  { 0, RESOURCE_ID_PT_PT_NAMES }, // 4 = Portuguese
 // ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', u'S\xe1b', 'Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez', 'am', 'pm']

 // de_DE
  { 0, RESOURCE_ID_DE_DE_NAMES }, // 5 = German
 // ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'Jan', 'Feb', u'M\xe4rz', 'Apr', 'Mai', 'Juni', 'Juli', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez', 'vorm', 'nach']

 // nl_NL
  { 0, RESOURCE_ID_NL_NL_NAMES }, // 6 = Dutch
 // ['Zo', 'Ma', 'Di', 'Wo', 'Do', 'Vr', 'Za', 'Jan', 'Feb', 'Mrt', 'Apr', 'Mei', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dec', 'am', 'pm']

 // da_DK
  { 0, RESOURCE_ID_DA_DK_NAMES }, // 7 = Danish
 // [u'S\xf8n', 'Man', 'Tir', 'Ons', 'Tor', 'Fre', u'L\xf8r', 'Jan', 'Feb', 'Mar', 'Apr', 'Maj', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dec', 'am', 'pm']

 // sv_SE
  { 0, RESOURCE_ID_SV_SE_NAMES }, // 8 = Swedish
 // [u'S\xf6n', u'M\xe5n', 'Tis', 'Ons', 'Tor', 'Fre', u'L\xf6r', 'Jan', 'Feb', 'Mars', 'Apr', 'Maj', 'Juni', 'Juli', 'Aug', 'Sep', 'Okt', 'Nov', 'Dec', 'fm', 'em']

 // is_IS
  { 0, RESOURCE_ID_IS_IS_NAMES }, // 9 = Icelandic
 // ['Sun', u'M\xe1n', u'\xderi', u'Mi\xf0', 'Fim', u'F\xf6s', 'Lau', 'Jan', 'Feb', 'Mar', 'Apr', u'Ma\xed', u'J\xfan', u'J\xfal', u'\xc1g\xfa', 'Sep', 'Okt', u'N\xf3v', 'Des', 'fh', 'eh']

 // tl
  { 0, RESOURCE_ID_TL_NAMES }, // 10 = Tagalog
 // ['Lin', 'Lun', 'Mar', 'Miy', 'Huw', 'Biy', 'Sab', 'Ene', 'Peb', 'Mar', 'Abr', 'May', 'Hun', 'Hul', 'Ago', 'Set', 'Okt', 'Nob', 'Dis', 'am', 'pm']

 // el_GR
  { 1, RESOURCE_ID_EL_GR_NAMES }, // 11 = Greek
 // [u'\u039a\u03c5\u03c1', u'\u0394\u03b5\u03c5', u'\u03a4\u03c1\u03af', u'\u03a4\u03b5\u03c4', u'\u03a0\u03ad\u03bc', u'\u03a0\u03b1\u03c1', u'\u03a3\u03ac\u03b2', u'\u0399\u03b1\u03bd', u'\u03a6\u03b5\u03b2', u'\u039c\u03b1\u03c1', u'\u0391\u03c0\u03c1', u'\u039c\u03b1\u0390', u'\u0399\u03bf\u03c5\u03bd', u'\u0399\u03bf\u03c5\u03bb', u'\u0391\u03c5\u03b3', u'\u03a3\u03b5\u03c0', u'\u039f\u03ba\u03c4', u'\u039d\u03bf\u03b5', u'\u0394\u03b5\u03ba', u'\u03c0\u03bc', u'\u03bc\u03bc']

 // hu_HU
  { 0, RESOURCE_ID_HU_HU_NAMES }, // 12 = Hungarian
 // ['V', 'H', 'K', 'Sze', 'Cs', 'P', 'Szo', 'J', 'F', 'M', u'\xc1', 'M', 'J', 'J', 'A', 'Sz', 'O', 'N', 'D', 'de', 'du']

 // ru_RU
  { 2, RESOURCE_ID_RU_RU_NAMES }, // 13 = Russian
 // [u'\u0412\u0441', u'\u041f\u043d', u'\u0412\u0442', u'\u0421\u0440', u'\u0427\u0442', u'\u041f\u0442', u'\u0421\u0431', u'\u042f\u043d\u0432', u'\u0424\u0435\u0432', u'\u041c\u0430\u0440', u'\u0410\u043f\u0440', u'\u041c\u0430\u0439', u'\u0418\u044e\u043d', u'\u0418\u044e\u043b', u'\u0410\u0432\u0433', u'\u0421\u0435\u043d', u'\u041e\u043a\u0442', u'\u041d\u043e\u044f', u'\u0414\u0435\u043a', u'\u0434\u043e', u'\u043f\u043e\u0441\u043b']

 // pl_PL
  { 0, RESOURCE_ID_PL_PL_NAMES }, // 14 = Polish
 // ['N', 'P', 'W', u'\u015a', 'C', 'P', 'S', 'Sty', 'Lut', 'Mar', 'Kwi', 'Maj', 'Cze', 'Lip', 'Sie', 'Wrz', u'Pa\u017a', 'Lis', 'Gru', 'am', 'pm']

 // cs_CZ
  { 0, RESOURCE_ID_CS_CZ_NAMES }, // 15 = Czech
 // ['Ne', 'Po', u'\xdat', 'St', u'\u010ct', u'P\xe1', 'So', 'Led', u'\xdano', u'B\u0159e', 'Dub', u'Kv\u011b', u'\u010cvn', u'\u010cvc', 'Srp', u'Z\xe1\u0159', u'\u0158\xedj', 'Lis', 'Pro', 'am', 'pm']

 // hy_AM
  { 3, RESOURCE_ID_HY_AM_NAMES }, // 16 = Armenian
 // [u'\u053f\u056b\u0580', u'\u0535\u0580\u056f', u'\u0535\u0580\u0584', u'\u0549\u0580\u0584', u'\u0540\u0576\u0563', u'\u0548\u0582\u0580', u'\u0547\u0562\u0569', u'\u0540\u0576\u057e', u'\u0553\u057f\u057e', u'\u0544\u0580\u057f', u'\u0531\u057a\u0580', u'\u0544\u0575\u057d', u'\u0540\u0576\u057d', u'\u0540\u056c\u057d', u'\u0555\u0563\u057d', u'\u054d\u0565\u057a', u'\u0540\u0578\u056f', u'\u0546\u0578\u0575', u'\u0534\u0565\u056f', u'\u0561\u057c\u0561\u057b', u'\u0570\u0565\u057f\u0578']

 // tr_TR
  { 0, RESOURCE_ID_TR_TR_NAMES }, // 17 = Turkish
 // ['Paz', 'Pzt', 'Sal', u'\xc7ar', 'Per', 'Cum', 'Cmt', 'Oca', u'\u015eub', 'Mar', 'Nis', 'May', 'Haz', 'Tem', u'A\u011fu', 'Eyl', 'Eki', 'Kas', 'Ara', u'\xf6\xf6', u'\xf6s']

 // he_IL
  { 4, RESOURCE_ID_HE_IL_NAMES }, // 18 = Hebrew
 // [u'\u05f3\u05d0', u'\u05f3\u05d1', u'\u05f3\u05d2', u'\u05f3\u05d3', u'\u05f3\u05d4', u'\u05f3\u05d5', u'\u05f3\u05e9', u'\u05f3\u05d5\u05e0\u05d9', u'\u05f3\u05e8\u05d1\u05e4', u'\u05e5\u05e8\u05de', u'\u05f3\u05e8\u05e4\u05d0', u'\u05d9\u05d0\u05de', u'\u05d9\u05e0\u05d5\u05d9', u'\u05d9\u05dc\u05d5\u05d9', u'\u05f3\u05d2\u05d5\u05d0', u'\u05f3\u05d8\u05e4\u05e1', u'\u05f3\u05e7\u05d5\u05d0', u'\u05f3\u05d1\u05d5\u05e0', u'\u05f3\u05de\u05e6\u05d3', 'am', 'pm']

 // fa_IR
  { 5, RESOURCE_ID_FA_IR_NAMES }, // 19 = Farsi
 // [u'\u06cc', u'\u062f', u'\u0633', u'\u0686', u'\u067e', u'\u062c', u'\u0634', u'\u0698', u'\u0641', u'\u0645', u'\u0622', u'\u0645', u'\u0698', u'\u0698', u'\u0627', u'\u0633', u'\u0627', u'\u0646', u'\u062f', u'\u0635', u'\u0645']

 // ar_SA
  { 5, RESOURCE_ID_AR_SA_NAMES }, // 20 = Arabic
 // [u'\u062d', u'\u0646', u'\u062b', u'\u0631', u'\u062e', u'\u062c', u'\u0633', u'\u064a', u'\u0641', u'\u0645', u'\u0623', u'\u0648', u'\u0646', u'\u0644', u'\u063a', u'\u0633', u'\u0643', u'\u0628', u'\u062f', u'\u0635', u'\u0645']

 // zh_CN
  { 6, RESOURCE_ID_ZH_CN_NAMES }, // 21 = Chinese
 // [u'\u5468\u65e5', u'\u5468\u4e00', u'\u5468\u4e8c', u'\u5468\u4e09', u'\u5468\u56db', u'\u5468\u4e94', u'\u5468\u516d', u'1\u6708', u'2\u6708', u'3\u6708', u'4\u6708', u'5\u6708', u'6\u6708', u'7\u6708', u'8\u6708', u'9\u6708', u'10\u6708', u'11\u6708', u'12\u6708', u'\u4e0a\u5348', u'\u4e0b\u5348']

 // ja_JP
  { 7, RESOURCE_ID_JA_JP_NAMES }, // 22 = Japanese
 // [u'\u65e5', u'\u6708', u'\u706b', u'\u6c34', u'\u6728', u'\u91d1', u'\u571f', u'1\u6708', u'2\u6708', u'3\u6708', u'4\u6708', u'5\u6708', u'6\u6708', u'7\u6708', u'8\u6708', u'9\u6708', u'10\u6708', u'11\u6708', u'12\u6708', u'\u5348\u524d', u'\u5348\u5f8c']

 // ko_KR
  { 8, RESOURCE_ID_KO_KR_NAMES }, // 23 = Korean
 // [u'\uc77c', u'\uc6d4', u'\ud654', u'\uc218', u'\ubaa9', u'\uae08', u'\ud1a0', u'1\uc6d4', u'2\uc6d4', u'3\uc6d4', u'4\uc6d4', u'5\uc6d4', u'6\uc6d4', u'7\uc6d4', u'8\uc6d4', u'9\uc6d4', u'10\uc6d4', u'11\uc6d4', u'12\uc6d4', u'\uc624\uc804', u'\uc624\ud6c4']

 // th_TH
  { 9, RESOURCE_ID_TH_TH_NAMES }, // 24 = Thai
 // [u'\u0e2d\u0e32', u'\u0e08', u'\u0e2d', u'\u0e1e', u'\u0e1e\u0e24', u'\u0e28', u'\u0e2a', u'\u0e21\u0e04', u'\u0e01\u0e1e', u'\u0e21\u0e35\u0e04', u'\u0e40\u0e21\u0e22', u'\u0e1e\u0e04', u'\u0e21\u0e34\u0e22', u'\u0e01\u0e04', u'\u0e2a\u0e04', u'\u0e01\u0e22', u'\u0e15\u0e04', u'\u0e1e\u0e22', u'\u0e18\u0e04', u'\u0e01\u0e48\u0e2d\u0e19', u'\u0e2b\u0e25\u0e31\u0e07']

 // ta_IN
  { 10, RESOURCE_ID_TA_IN_NAMES }, // 25 = Tamil
 // [u'\u0b9e\u0bbe', u'\u0ba4\u0bbf', u'\u0b9a\u0bc6', u'\u0baa\u0bc1', u'\u0bb5\u0bbf', u'\u0bb5\u0bc6', u'\u0b9a', u'\u0b9c\u0ba9', u'\u0baa\u0bbf\u0baa\u0bcd', u'\u0bae\u0bbe\u0bb0\u0bcd', u'\u0b8f\u0baa\u0bcd', u'\u0bae\u0bc7', u'\u0b9c\u0bc2\u0ba9\u0bcd', u'\u0b9c\u0bc2\u0bb2\u0bc8', u'\u0b86\u0b95', u'\u0b9a\u0bc6\u0baa\u0bcd', u'\u0b85\u0b95\u0bcd', u'\u0ba8\u0bb5', u'\u0b9f\u0bbf\u0b9a', u'\u0bae\u0bc1', u'\u0baa\u0bbf']

 // hi_IN
  { 11, RESOURCE_ID_HI_IN_NAMES }, // 26 = Hindi
 // [u'\u0930', u'\u0938\u094b', u'\u092e\u0902', u'\u092c\u0941', u'\u0917\u0941', u'\u0936\u0941', u'\u0936', u'\u091c', u'\u092b\u093c', u'\u092e\u093e', u'\u0905', u'\u092e', u'\u091c\u0942', u'\u091c\u0941', u'\u0905', u'\u0938\u093f', u'\u0905', u'\u0928', u'\u0926\u093f', u'\u092a\u0942\u0930\u094d\u0935', u'\u0905\u092a\u0930']

 // bg_BG
  { 2, RESOURCE_ID_BG_BG_NAMES }, // 27 = Bulgarian
 // [u'\u041d\u0434', u'\u041f\u043d', u'\u0412\u0442', u'\u0421\u0440', u'\u0427\u0442', u'\u041f\u0442', u'\u0421\u0431', u'\u042f\u043d', u'\u0424\u0435\u0432\u0440', u'\u041c\u0430\u0440\u0442', u'\u0410\u043f\u0440', u'\u041c\u0430\u0439', u'\u042e\u043d\u0438', u'\u042e\u043b\u0438', u'\u0410\u0432\u0433', u'\u0421\u0435\u043f\u0442', u'\u041e\u043a\u0442', u'\u041d\u043e\u0435\u043c', u'\u0414\u0435\u043a', u'\u043f\u0440\u043e\u0431', u'\u0441\u043b\u043e\u0431']

 // nb_NO
  { 0, RESOURCE_ID_NB_NO_NAMES }, // 28 = Norwegian
 // [u'S\xf8', 'Ma', 'Ti', 'On', 'To', 'Fr', u'L\xf8', 'Jan', 'Feb', 'Mar', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Des', 'am', 'pm']

};

int num_langs = 29;
// maximum characters: 15
#define DATE_NAMES_MAX_BUFFER 182

#define NUM_DATE_LANG_FONTS 12
struct FontPlacement date_lang_font_placement[NUM_DATE_LANG_FONTS] = {
#if defined(PBL_PLATFORM_EMERY)
{ RESOURCE_ID_DAY_FONT_LATIN_22, -1 },
{ RESOURCE_ID_DAY_FONT_EL_19, 1 },
{ RESOURCE_ID_DAY_FONT_RU_19, 1 },
{ RESOURCE_ID_DAY_FONT_HY_19, 1 },
{ RESOURCE_ID_DAY_FONT_RTL_HE_19, 1 },
{ RESOURCE_ID_DAY_FONT_RTL_AR_19, 1 },
{ RESOURCE_ID_DAY_FONT_ZH_22, -1 },
{ RESOURCE_ID_DAY_FONT_JA_22, -1 },
{ RESOURCE_ID_DAY_FONT_KO_22, -2 },
{ RESOURCE_ID_DAY_FONT_TH_22, -1 },
{ RESOURCE_ID_DAY_FONT_TA_22, -2 },
{ RESOURCE_ID_DAY_FONT_HI_22, 0 },
#elif defined(PBL_PLATFORM_APLITE) || defined(PBL_PLATFORM_BASALT) || defined(PBL_PLATFORM_DIORITE)
{ RESOURCE_ID_DAY_FONT_LATIN_16, -1 },
{ RESOURCE_ID_DAY_FONT_EL_14, 1 },
{ RESOURCE_ID_DAY_FONT_RU_14, 1 },
{ RESOURCE_ID_DAY_FONT_HY_14, 1 },
{ RESOURCE_ID_DAY_FONT_RTL_HE_14, 1 },
{ RESOURCE_ID_DAY_FONT_RTL_AR_14, 1 },
{ RESOURCE_ID_DAY_FONT_ZH_16, -1 },
{ RESOURCE_ID_DAY_FONT_JA_16, -1 },
{ RESOURCE_ID_DAY_FONT_KO_16, -2 },
{ RESOURCE_ID_DAY_FONT_TH_16, -1 },
{ RESOURCE_ID_DAY_FONT_TA_16, -2 },
{ RESOURCE_ID_DAY_FONT_HI_16, 0 },
#elif defined(PBL_PLATFORM_CHALK)
{ RESOURCE_ID_DAY_FONT_LATIN_18, -1 },
{ RESOURCE_ID_DAY_FONT_EL_16, 1 },
{ RESOURCE_ID_DAY_FONT_RU_16, 1 },
{ RESOURCE_ID_DAY_FONT_HY_16, 1 },
{ RESOURCE_ID_DAY_FONT_RTL_HE_16, 1 },
{ RESOURCE_ID_DAY_FONT_RTL_AR_16, 1 },
{ RESOURCE_ID_DAY_FONT_ZH_18, -1 },
{ RESOURCE_ID_DAY_FONT_JA_18, -1 },
{ RESOURCE_ID_DAY_FONT_KO_18, -2 },
{ RESOURCE_ID_DAY_FONT_TH_18, -1 },
{ RESOURCE_ID_DAY_FONT_TA_18, -2 },
{ RESOURCE_ID_DAY_FONT_HI_18, 0 },
#endif
};
