// Generated by make_lang.py

LangDef lang_table[27] = {
  { "en_US", 0, RESOURCE_ID_EN_US_WEEKDAY_NAMES, RESOURCE_ID_EN_US_MONTH_NAMES }, // 0 = English
 //   Weekdays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
 //   Months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

  { "fr_FR", 0, RESOURCE_ID_FR_FR_WEEKDAY_NAMES, RESOURCE_ID_FR_FR_MONTH_NAMES }, // 1 = French
 //   Weekdays: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam']
 //   Months: ['Janv', u'F\xe9vr', 'Mars', 'Avr', 'Mai', 'Juin', 'Juil', u'Ao\xfbt', 'Sept', 'Oct', 'Nov', u'D\xe9c']

  { "it_IT", 0, RESOURCE_ID_IT_IT_WEEKDAY_NAMES, RESOURCE_ID_IT_IT_MONTH_NAMES }, // 2 = Italian
 //   Weekdays: ['Dom', 'Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab']
 //   Months: ['Gen', 'Feb', 'Mar', 'Apr', 'Mag', 'Giu', 'Lug', 'Ago', 'Set', 'Ott', 'Nov', 'Dic']

  { "es_ES", 0, RESOURCE_ID_ES_ES_WEEKDAY_NAMES, RESOURCE_ID_ES_ES_MONTH_NAMES }, // 3 = Spanish
 //   Weekdays: ['Dom', 'Lun', 'Mar', u'Mi\xe9', 'Jue', 'Vie', u'S\xe1b']
 //   Months: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sept', 'Oct', 'Nov', 'Dic']

  { "pt_PT", 0, RESOURCE_ID_PT_PT_WEEKDAY_NAMES, RESOURCE_ID_PT_PT_MONTH_NAMES }, // 4 = Portuguese
 //   Weekdays: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', u'S\xe1b']
 //   Months: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']

  { "de_DE", 0, RESOURCE_ID_DE_DE_WEEKDAY_NAMES, RESOURCE_ID_DE_DE_MONTH_NAMES }, // 5 = German
 //   Weekdays: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa']
 //   Months: ['Jan', 'Feb', u'M\xe4r', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez']

  { "nl_NL", 0, RESOURCE_ID_NL_NL_WEEKDAY_NAMES, RESOURCE_ID_NL_NL_MONTH_NAMES }, // 6 = Dutch
 //   Weekdays: ['Zo', 'Ma', 'Di', 'Wo', 'Do', 'Vr', 'Za']
 //   Months: ['Jan', 'Feb', 'Mrt', 'Apr', 'Mei', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dec']

  { "da_DK", 0, RESOURCE_ID_DA_DK_WEEKDAY_NAMES, RESOURCE_ID_DA_DK_MONTH_NAMES }, // 7 = Danish
 //   Weekdays: [u'S\xf8n', 'Man', 'Tir', 'Ons', 'Tor', 'Fre', u'L\xf8r']
 //   Months: ['Jan', 'Feb', 'Mar', 'Apr', 'Maj', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dec']

  { "sv_SE", 0, RESOURCE_ID_SV_SE_WEEKDAY_NAMES, RESOURCE_ID_SV_SE_MONTH_NAMES }, // 8 = Swedish
 //   Weekdays: [u'S\xf6n', u'M\xe5n', 'Tis', 'Ons', 'Tor', 'Fre', u'L\xf6r']
 //   Months: ['Jan', 'Feb', 'Mar', 'Apr', 'Maj', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dec']

  { "is_IS", 0, RESOURCE_ID_IS_IS_WEEKDAY_NAMES, RESOURCE_ID_IS_IS_MONTH_NAMES }, // 9 = Icelandic
 //   Weekdays: ['Sun', u'M\xe1n', u'\xderi', u'Mi\xf0', 'Fim', u'F\xf6s', 'Lau']
 //   Months: ['Jan', 'Feb', 'Mar', 'Apr', u'Ma\xed', u'J\xfan', u'J\xfal', u'\xc1g\xfa', 'Sep', 'Okt', u'N\xf3v', 'Des']

  { "tl", 0, RESOURCE_ID_TL_WEEKDAY_NAMES, RESOURCE_ID_TL_MONTH_NAMES }, // 10 = Tagalog
 //   Weekdays: ['Lin', 'Lun', 'Mar', 'Miy', 'Huw', 'Biy', 'Sab']
 //   Months: ['Ene', 'Peb', 'Mar', 'Abr', 'May', 'Hun', 'Hul', 'Ago', 'Set', 'Okt', 'Nob', 'Dis']

  { "el_GR", 1, RESOURCE_ID_EL_GR_WEEKDAY_NAMES, RESOURCE_ID_EL_GR_MONTH_NAMES }, // 11 = Greek
 //   Weekdays: [u'\u039a\u03c5\u03c1', u'\u0394\u03b5\u03c5', u'\u03a4\u03c1\u03af', u'\u03a4\u03b5\u03c4', u'\u03a0\u03ad\u03bc', u'\u03a0\u03b1\u03c1', u'\u03a3\u03ac\u03b2']
 //   Months: [u'\u0399\u03b1\u03bd', u'\u03a6\u03b5\u03b2', u'\u039c\u03ac\u03c1', u'\u0391\u03c0\u03c1', u'\u039c\u03ac\u03b9', u'\u0399\u03bf\u03cd\u03bd', u'\u0399\u03bf\u03cd\u03bb', u'\u0391\u03cd\u03b3', u'\u03a3\u03b5\u03c0', u'\u039f\u03ba\u03c4', u'\u039d\u03bf\u03ad', u'\u0394\u03b5\u03ba']

  { "hu_HU", 0, RESOURCE_ID_HU_HU_WEEKDAY_NAMES, RESOURCE_ID_HU_HU_MONTH_NAMES }, // 12 = Hungarian
 //   Weekdays: ['V', 'H', 'K', 'Sze', 'Cs', 'P', 'Szo']
 //   Months: ['J', 'F', 'M', u'\xc1', 'M', 'J', 'J', 'A', 'Sz', 'O', 'N', 'D']

  { "ru_RU", 1, RESOURCE_ID_RU_RU_WEEKDAY_NAMES, RESOURCE_ID_RU_RU_MONTH_NAMES }, // 13 = Russian
 //   Weekdays: [u'\u0412\u0441', u'\u041f\u043d', u'\u0412\u0442', u'\u0421\u0440', u'\u0427\u0442', u'\u041f\u0442', u'\u0421\u0431']
 //   Months: [u'\u042f\u043d\u0432', u'\u0424\u0435\u0432\u0440', u'\u041c\u0430\u0440\u0442', u'\u0410\u043f\u0440', u'\u041c\u0430\u0439', u'\u0418\u044e\u043d\u044c', u'\u0418\u044e\u043b\u044c', u'\u0410\u0432\u0433', u'\u0421\u0435\u043d\u0442', u'\u041e\u043a\u0442', u'\u041d\u043e\u044f\u0431', u'\u0414\u0435\u043a']

  { "pl_PL", 0, RESOURCE_ID_PL_PL_WEEKDAY_NAMES, RESOURCE_ID_PL_PL_MONTH_NAMES }, // 14 = Polish
 //   Weekdays: ['N', 'P', 'W', u'\u015a', 'C', 'P', 'S']
 //   Months: ['Sty', 'Lut', 'Mar', 'Kwi', 'Maj', 'Cze', 'Lip', 'Sie', 'Wrz', u'Pa\u017a', 'Lis', 'Gru']

  { "cs_CZ", 0, RESOURCE_ID_CS_CZ_WEEKDAY_NAMES, RESOURCE_ID_CS_CZ_MONTH_NAMES }, // 15 = Czech
 //   Weekdays: ['Ne', 'Po', u'\xdat', 'St', u'\u010ct', u'P\xe1', 'So']
 //   Months: ['Led', u'\xdano', u'B\u0159e', 'Dub', u'Kv\u011b', u'\u010cvn', u'\u010cvc', 'Srp', u'Z\xe1\u0159', u'\u0158\xedj', 'Lis', 'Pro']

  { "hy_AM", 1, RESOURCE_ID_HY_AM_WEEKDAY_NAMES, RESOURCE_ID_HY_AM_MONTH_NAMES }, // 16 = Armenian
 //   Weekdays: [u'\u053f\u056b\u0580', u'\u0535\u0580\u056f', u'\u0535\u0580\u0584', u'\u0549\u0580\u0584', u'\u0540\u0576\u0563', u'\u0548\u0582\u0580', u'\u0547\u0562\u0569']
 //   Months: [u'\u0540\u0576\u057e', u'\u0553\u057f\u057e', u'\u0544\u0580\u057f', u'\u0531\u057a\u0580', u'\u0544\u0575\u057d', u'\u0540\u0576\u057d', u'\u0540\u056c\u057d', u'\u0555\u0563\u057d', u'\u054d\u057a\u057f', u'\u0540\u056f\u057f', u'\u0546\u0575\u0574', u'\u0534\u056f\u057f']

  { "tr_TR", 0, RESOURCE_ID_TR_TR_WEEKDAY_NAMES, RESOURCE_ID_TR_TR_MONTH_NAMES }, // 17 = Turkish
 //   Weekdays: ['Paz', 'Pzt', 'Sal', u'\xc7ar', 'Per', 'Cum', 'Cmt']
 //   Months: ['Oca', u'\u015eub', 'Mar', 'Nis', 'May', 'Haz', 'Tem', u'A\u011fu', 'Eyl', 'Eki', 'Kas', 'Ara']

  { "he_IL", 2, RESOURCE_ID_HE_IL_WEEKDAY_NAMES, RESOURCE_ID_HE_IL_MONTH_NAMES }, // 18 = Hebrew
 //   Weekdays: [u'\u05f3\u05d0', u'\u05f3\u05d1', u'\u05f3\u05d2', u'\u05f3\u05d3', u'\u05f3\u05d4', u'\u05f3\u05d5', u'\u05f3\u05e9']
 //   Months: [u'\u05f3\u05d5\u05e0\u05d9', u'\u05f3\u05e8\u05d1\u05e4', u'\u05e5\u05e8\u05de', u'\u05f3\u05e8\u05e4\u05d0', u'\u05d9\u05d0\u05de', u'\u05f3\u05e0\u05d5\u05d9', u'\u05f3\u05dc\u05d5\u05d9', u'\u05f3\u05d2\u05d5\u05d0', u'\u05f3\u05d8\u05e4\u05e1', u'\u05f3\u05e7\u05d5\u05d0', u'\u05f3\u05d1\u05d5\u05e0', u'\u05f3\u05de\u05e6\u05d3']

  { "fa_IR", 2, RESOURCE_ID_FA_IR_WEEKDAY_NAMES, RESOURCE_ID_FA_IR_MONTH_NAMES }, // 19 = Farsi
 //   Weekdays: [u'\u06cc', u'\u062f', u'\u0633', u'\u0686', u'\u067e', u'\u062c', u'\u0634']
 //   Months: [u'\u0698', u'\u0641', u'\u0645', u'\u0622', u'\u0645', u'\u0698', u'\u0698', u'\u0627', u'\u0633', u'\u0627', u'\u0646', u'\u062f']

  { "ar_SA", 2, RESOURCE_ID_AR_SA_WEEKDAY_NAMES, RESOURCE_ID_AR_SA_MONTH_NAMES }, // 20 = Arabic
 //   Weekdays: [u'\u062d', u'\u0646', u'\u062b', u'\u0631', u'\u062e', u'\u062c', u'\u0633']
 //   Months: [u'\u064a', u'\u0641', u'\u0645', u'\u0623', u'\u0648', u'\u0646', u'\u0644', u'\u063a', u'\u0633', u'\u0643', u'\u0628', u'\u062f']

  { "zh_CN", 3, RESOURCE_ID_ZH_CN_WEEKDAY_NAMES, RESOURCE_ID_ZH_CN_MONTH_NAMES }, // 21 = Chinese
 //   Weekdays: [u'\u5468\u65e5', u'\u5468\u4e00', u'\u5468\u4e8c', u'\u5468\u4e09', u'\u5468\u56db', u'\u5468\u4e94', u'\u5468\u516d']
 //   Months: [u'1\u6708', u'2\u6708', u'3\u6708', u'4\u6708', u'5\u6708', u'6\u6708', u'7\u6708', u'8\u6708', u'9\u6708', u'10\u6708', u'11\u6708', u'12\u6708']

  { "ja_JP", 4, RESOURCE_ID_JA_JP_WEEKDAY_NAMES, RESOURCE_ID_JA_JP_MONTH_NAMES }, // 22 = Japanese
 //   Weekdays: [u'\u65e5', u'\u6708', u'\u706b', u'\u6c34', u'\u6728', u'\u91d1', u'\u571f']
 //   Months: [u'1\u6708', u'2\u6708', u'3\u6708', u'4\u6708', u'5\u6708', u'6\u6708', u'7\u6708', u'8\u6708', u'9\u6708', u'10\u6708', u'11\u6708', u'12\u6708']

  { "ko_KR", 5, RESOURCE_ID_KO_KR_WEEKDAY_NAMES, RESOURCE_ID_KO_KR_MONTH_NAMES }, // 23 = Korean
 //   Weekdays: [u'\uc77c', u'\uc6d4', u'\ud654', u'\uc218', u'\ubaa9', u'\uae08', u'\ud1a0']
 //   Months: [u'1\uc6d4', u'2\uc6d4', u'3\uc6d4', u'4\uc6d4', u'5\uc6d4', u'6\uc6d4', u'7\uc6d4', u'8\uc6d4', u'9\uc6d4', u'10\uc6d4', u'11\uc6d4', u'12\uc6d4']

  { "th_TH", 6, RESOURCE_ID_TH_TH_WEEKDAY_NAMES, RESOURCE_ID_TH_TH_MONTH_NAMES }, // 24 = Thai
 //   Weekdays: [u'\u0e2d\u0e32', u'\u0e08', u'\u0e2d', u'\u0e1e', u'\u0e1e\u0e24', u'\u0e28', u'\u0e2a']
 //   Months: [u'\u0e21\u0e04', u'\u0e01\u0e1e', u'\u0e21\u0e35\u0e04', u'\u0e40\u0e21\u0e22', u'\u0e1e\u0e04', u'\u0e21\u0e34\u0e22', u'\u0e01\u0e04', u'\u0e2a\u0e04', u'\u0e01\u0e22', u'\u0e15\u0e04', u'\u0e1e\u0e22', u'\u0e18\u0e04']

  { "ta_IN", 7, RESOURCE_ID_TA_IN_WEEKDAY_NAMES, RESOURCE_ID_TA_IN_MONTH_NAMES }, // 25 = Tamil
 //   Weekdays: [u'\u0b9e\u0bbe', u'\u0ba4\u0bbf', u'\u0b9a\u0bc6', u'\u0baa\u0bc1', u'\u0bb5\u0bbf', u'\u0bb5\u0bc6', u'\u0b9a']
 //   Months: [u'\u0b9c\u0ba9', u'\u0baa\u0bbf\u0baa\u0bcd', u'\u0bae\u0bbe\u0bb0\u0bcd', u'\u0b8f\u0baa\u0bcd', u'\u0bae\u0bc7', u'\u0b9c\u0bc2\u0ba9\u0bcd', u'\u0b9c\u0bc2\u0bb2\u0bc8', u'\u0b86\u0b95', u'\u0b9a\u0bc6\u0baa\u0bcd', u'\u0b85\u0b95\u0bcd', u'\u0ba8\u0bb5', u'\u0b9f\u0bbf\u0b9a']

  { "hi_IN", 8, RESOURCE_ID_HI_IN_WEEKDAY_NAMES, RESOURCE_ID_HI_IN_MONTH_NAMES }, // 26 = Hindi
 //   Weekdays: [u'\u0930', u'\u0938\u094b', u'\u092e\u0902', u'\u092c\u0941', u'\u0917\u0941', u'\u0936\u0941', u'\u0936']
 //   Months: [u'\u091c', u'\u092b\u093c', u'\u092e\u093e', u'\u0905', u'\u092e', u'\u091c\u0942', u'\u091c\u0941', u'\u0905', u'\u0938\u093f', u'\u0905', u'\u0928', u'\u0926\u093f']

};

int num_langs = 27;
// maximum characters: 12
#define DAY_NAMES_MAX_BUFFER 122

