#! /usr/bin/env python

import sys
import os
import getopt
import locale

help = """
make_lang.py

Re-run this script to generate lang_table.c and lang_fonts.json in
the resources directory, based on the system language data.

make_lang.py [opts]
"""

fontChoices = [ 'latin', 'extended', 'zh', 'ja', 'ko' ]

# Font filenames and pixel sizes.
fontNames = {
    'latin' : ('ArchivoNarrow-Bold.ttf', 16),
    'extended' : ('DejaVuSansCondensed-Bold.ttf', 14),
    'zh' : ('wqy-microhei.ttc', 16),
    'ja' : ('TakaoPGothic.ttf', 16),
    'ko' : ('UnDotum.ttf', 16),
    }

# This list is duplicated in html/rosewright_X_configure.js.
langs = [
    [ 'en_US', 'English', 'latin' ],
    [ 'fr_FR', 'French', 'latin' ],
    [ 'it_IT', 'Italian', 'latin' ],
    [ 'es_ES', 'Spanish', 'latin' ],
    [ 'pt_PT', 'Portuguese', 'latin' ],
    [ 'de_DE', 'German', 'latin' ],
    [ 'nl_NL', 'Dutch', 'latin' ],
    [ 'da_DK', 'Danish', 'latin' ],
    [ 'sv_SE', 'Swedish', 'latin' ],
    [ 'is_IS', 'Icelandic', 'latin' ],
    ];

# Non-standard font required for these:
langs += [
    [ 'el_GR', 'Greek', 'extended' ],
    [ 'hu_HU', 'Hungarian', 'latin' ],
    [ 'ru_RU', 'Russian', 'extended' ],
    [ 'pl_PL', 'Polish', 'latin' ],
    [ 'cs_CZ', 'Czech', 'latin' ],
    ]

# CJK is its own set of categories.
langs += [
    [ 'zh_CN', 'Chinese', 'zh' ],
    [ 'ja_JP', 'Japanese', 'ja' ],
    [ 'ko_KR', 'Korean', 'ko' ],
    ]

# Attempt to determine the directory in which we're operating.
rootDir = os.path.dirname(__file__) or '.'
resourcesDir = rootDir

neededChars = {}

def makeDates(generatedTable, li):
    localeName, langName, fontKey = langs[li]
    fontIndex = fontChoices.index(fontKey)
    print localeName
    locale.setlocale(locale.LC_ALL, localeName + '.UTF-8')

    neededChars.setdefault(fontKey, set())
    weekdayNames = []
    for sym in [locale.ABDAY_1, locale.ABDAY_2, locale.ABDAY_3, locale.ABDAY_4, locale.ABDAY_5, locale.ABDAY_6, locale.ABDAY_7]:
        name = locale.nl_langinfo(sym)
        name = name.decode('utf-8')
        if name[-1] == '.':
            # Sometimes the abbreviation ends with a dot.
            name = name[:-1]
        # Ensure the first letter is uppercase for consistency.
        name = name[0].upper() + name[1:]
        for char in name:
            neededChars[fontKey].add(ord(char))
        name = name.encode('utf-8')

        if '"' in name or name.encode('string_escape') != name:
            # The text has some fancy characters.  We can't just pass
            # string_escape, since that's not 100% C compatible.
            # Instead, we'll aggressively hexify every character.
            name = ''.join(map(lambda c: '\\x%02x' % (ord(c)), name))
        weekdayNames.append(' \"%s\",' % (name))
        
    print >> generatedTable, """  { "%s", {%s }, %s }, // %s = %s""" % (localeName, ''.join(weekdayNames), fontIndex, li, langName)

def makeCharacterRegex(chars):
    chars = list(chars)
    chars.sort()

    i = 0
    r = [[chars[i], chars[i]]]
    i += 1
    while i < len(chars):
        if chars[i] == r[-1][1] + 1:
            # This character extends the current range.
            r[-1][1] = chars[i]
        else:
            # This character begins a new range.
            r.append([chars[i], chars[i]])
        i += 1

    # Now build a sequence of strings of the form \uXXXX or \uXXXX-\uXXXX.
    s = ''
    for a, b in r:
        if a == b:
            s += '\u%04x' % (a)
        else:
            s += '\u%04x-\u%04x' % (a, b)

    return s

def makeLang():
    generatedTable = open('%s/lang_table.c' % (resourcesDir), 'w')
    print >> generatedTable, '// Generated by make_lang.py\n'

    numLangs = len(langs)
    print >> generatedTable, "LangDef lang_table[%s] = {" % (numLangs)

    for li in range(numLangs):
        makeDates(generatedTable, li)

    print >> generatedTable, "};\n"

    print >> generatedTable, "int num_langs = %s;\n" % (numLangs)

    generatedJson = open('%s/lang_fonts.json' % (resourcesDir), 'w')

    jsonEntry = """    {
      "type": "font",
      "characterRegex": "[%(regex)s]",
      "name": "DAY_FONT_%(upperKey)s_%(size)s",
      "file": "%(filename)s"
    },
"""    

    for fontKey in fontChoices:
        filename, size = fontNames[fontKey]
        print >> generatedJson, jsonEntry % {
            'regex' : makeCharacterRegex(neededChars[fontKey]),
            'upperKey' : fontKey.upper(),
            'size' : size,
            'filename' : filename,
            }

# Main.
try:
    opts, args = getopt.getopt(sys.argv[1:], 'h')
except getopt.error, msg:
    usage(1, msg)

for opt, arg in opts:
    if opt == '-h':
        usage(0)

makeLang()
