#! /usr/bin/env fontforge

# Run this Python script with FontForge to generate day_font.otf with
# the required subset of characters extracted from the source font.
# The subset is read from lang_characters.py, which was generated by
# make_lang.py.

import fontforge
import sys
import lang_characters
import os

# Attempt to determine the directory in which we're operating.
rootDir = os.path.dirname(__file__) or '.'
resourcesDir = rootDir

# I like ArchivoNarrow for its cleanliness, but it lacks some of the
# extended characters for Greek and Russion, so I fill in the
# needed characters from OpenSans.
sourceFilenames = {
    'latin' : 'ArchivoNarrow-Bold.ttf',
    'extended' : 'OpenSans-CondBold.ttf',
    }

characters = {
    'latin' : [],
    'extended' : [],
    }

for ch in lang_characters.characters:
    if ch < 0x250:
        characters['latin'].append(ch)
    else:
        characters['extended'].append(ch)

target = fontforge.new()

for charset in ['latin', 'extended']:
    selection = [('unicode', 'singletons')] + characters[charset]

    sourceFilename = '%s/%s' % (resourcesDir, sourceFilenames[charset])

    source = fontforge.open(sourceFilename)
    print source
    source.selection.select(*selection)
    source.copy()
    target.paste()

print target
targetFilename = '%s/day_font.otf' % (resourcesDir)
target.generate(targetFilename)
